#pragma once
#include "WJDefines.h"

#define WJSHANDLDE IWJLibInterface*
#define WJMFTREADER IWJMftReader*
#define WJSVOLUME IWJVolume*
#define WJSINDEXFILE IWJMftIndexFile*
#define WJSFILEDATA IWJMftFileData*
#define WJSFILE IWJMftFileRecord*

	enum CALLBACK_ACTION
	{
		CALLBACK_ACTION_BEGIN,
		CALLBACK_ACTION_END,
		CALLBACK_ACTION_ERROR,
		CALLBACK_ACTION_CONTINUE,
		CALLBACK_ACTION_NAMEMATCH,
		CALLBACK_ACTION_NAMENOTMATCH,
		CALLBACK_ACTION_MINSIZE,
		CALLBACK_ACTION_MAXSIZE,
		CALLBACK_ACTION_FILETYPE,
		CALLBACK_ACTION_FILEINFO,
		CALLBACK_ACTION_FILECHANGE
	};
	
	typedef union CALLBACK_PARAM
	{
		WJ_ERROR_CODE code;
		TCHAR** NameMatchs;
		TCHAR** NameNotMatchs;
		INT64 MinSize;
		INT64 MaxSize;
		BYTE FileOrDir;
		struct
		{
			WJSFILE File;
			TCHAR* Path;
		}; 
		struct
		{
			WJFILE_CHANGED_REASON reason;
			WJSFILE ChangeFile;
		};
		struct
		{
			WJSFILE DelFile;
			TCHAR* Path;
			//PFILE_DATA_STREAM pStream;
		};
	}*PCALLBACK_PARAM;

	typedef BOOL(WJS_CALL_BACK WJS_CALL)(CALLBACK_ACTION, PCALLBACK_PARAM, PVOID);

	WJS_API WJSHANDLDE WJS_CALL WJSOpen();
	WJS_API VOID WJS_CALL WJSClose();

	//interface WJS_API IWJMftFileRecord//: IInterface
	//{
	WJS_API UINT64 WJS_CALL WJSFileReferences(WJSFILE);                     //数组所属目录
	WJS_API UINT64 WJS_CALL WJSParentDircetoryReferences(WJSFILE);                     //数组所属目录
	WJS_API BOOL WJS_CALL WJSIsDir(WJSFILE);
	WJS_API PFILETIME WJS_CALL WJSCreationTime(WJSFILE);
	WJS_API PFILETIME WJS_CALL WJSChangeTime(WJSFILE);
	WJS_API PFILETIME WJS_CALL WJSLastWriteTime(WJSFILE);
	WJS_API PFILETIME WJS_CALL WJSLastAccessTime(WJSFILE);
	WJS_API UINT64 WJS_CALL WJSSize(WJSFILE);
	WJS_API USHORT WJS_CALL WJSFileNameLength(WJSFILE);
	WJS_API WCHAR* WJS_CALL WJSFileName(WJSFILE);
	WJS_API WCHAR* WJS_CALL WJSFilePath(WJSFILE);
	WJS_API PVOID WJS_CALL WJSGetData(WJSFILE, PDWORD);
	WJS_API VOID WJS_CALL WJSRuns(WJSFILE);

	//};

	//用于动态库导出接口。
	//interface WJS_API IWJVolume
	//{
	WJS_API HANDLE WJS_CALL WJSOpenHandle(WJSVOLUME volume);
	WJS_API VOID WJS_CALL WJSCloseHandle(WJSVOLUME volume);
	WJS_API const TCHAR* WJS_CALL WJSGetVolumeGuid(WJSVOLUME volume);
	WJS_API const TCHAR* WJS_CALL WJSGetVolumePath(WJSVOLUME volume);
	WJS_API const TCHAR* WJS_CALL WJSGetVolumeLabel(WJSVOLUME volume);
	WJS_API WJFILESYSTEM_TYPE WJS_CALL WJSGetFileSystem(WJSVOLUME volume);
	WJS_API MEDIA_TYPE WJS_CALL WJSGetMediaType(WJSVOLUME volume);
	WJS_API UINT64 WJS_CALL WJSGetTotalSize(WJSVOLUME volume);
	//};

	//interface WJS_API IWJMftIndexFile
	//{
	//WJS_API VOID WJS_CALL WJSIndexFileClose(WJSINDEXFILE);
	//};

	//interface WJS_API IWJLibInterface
	//{
	WJS_API UINT WJS_CALL WJSGetVolumeCount();
	WJS_API WJSVOLUME WJS_CALL WJSGetVolume(int);
	//WJS_API WJSINDEXFILE WJS_CALL WJSRenewIndexFile(WJSVOLUME, const TCHAR* Filename, WJS_CALL_BACK*, PVOID);
	WJS_API WJ_ERROR_CODE WJS_CALL WJSSearchVolume(WJSVOLUME, WJS_CALL_BACK*, PVOID);
	//WJS_API WJ_ERROR_CODE WJS_CALL WJSSearchIndexFile(WJSFILE, WJS_CALL_BACK*, PVOID);
	//WJS_API WJ_ERROR_CODE WJS_CALL WJSListenFileChaged(WJSVOLUME, WJSINDEXFILE*, WJS_CALL_BACK*, PVOID);
	WJS_API WJ_ERROR_CODE WJS_CALL WJSSearchDeletedFile(WJSVOLUME, WJS_CALL_BACK*, PVOID);
	//};
