// LdShellExtend.idl : LdShellExtend 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(LdShellExtend.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(B15A85DA-2828-443D-A509-479D8A9E035D),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface ILdContextMenu : IDispatch{
};
[
	uuid(AD39E2F7-6CEC-4EC8-9273-A6A9993EBF09),
	version(1.0),
]
library LdShellExtendLib
{
	importlib("stdole2.tlb");
	[
		uuid(7C4429E3-0593-45DC-BF37-F2CBCEFB27F2)		
	]
	coclass LdContextMenu
	{
		[default] interface ILdContextMenu;
	};
};

